theme: jekyll-theme-cayman
title: PredFlow
tagline: Predictive coding using tensorflow
gems:
  - jekyll-paginate

paginate: 1
locale: "en"

author:
  name: Arno Granier
  url: https://github.com/arnogranier
