theme: jekyll-theme-cayman
gems:
  - jekyll-paginate
title: PredFlow
paginate: 1
locale: "en"
baseurl: ""

author:
  name: Arno Granier
  url: https://github.com/arnogranier

github:
  repository_url: https://github.com/arnogranier/PredFlow